Repository Trendyol/baklava, pull requests merged in 2022-08, with the labels that each got.

#190 chore: added vscode recommended extensions (#189)
  .gitignore
  .vscode/extensions.json
Labels: baklava-ds

#200 docs: add note for using inline styling at storybook components
  src/components/badge/bl-badge.stories.mdx
  src/components/button/bl-button.stories.mdx
  src/components/icon/bl-icon.stories.mdx
  src/components/input/bl-input.stories.mdx
  src/components/progress-indicator/bl-progress-indicator.stories.mdx
  src/components/tab-group/bl-tab-group.stories.mdx
  src/components/tab-group/tab-panel/bl-tab-panel.stories.mdx
  src/components/tab-group/tab/bl-tab.stories.mdx
  src/components/tooltip/bl-tooltip.stories.mdx
Labels: documentation, baklava-ds

#209 feat: minify css
  scripts/build.js
Labels: enhancement, baklava-ds

#213 chore: describe border radius variables
  docs/design-system/border-radius.stories.mdx
  src/components/tab-group/bl-tab-group.css
  src/components/tab-group/tab-panel/bl-tab-panel.css
  src/themes/default.css
Labels: baklava-ds

#214 docs: fix border radius rem variable
  docs/design-system/border-radius.stories.mdx
Labels: baklava-ds
